apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd
  namespace: argocd
spec:
  dnsNames:
    - rohin-dev.in
  secretName: argocd-app-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer