apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-app
spec:
  dnsNames:
    - rohin-dev.in
  secretName: argo-app-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
